<?php

return [

    'peinture-interieure' => [
        'meta_title' => 'Peinture intérieure à Évian et Thonon — Devigny Peinture, artisan qualifié',
        'meta_description' => 'Peinture intérieure professionnelle pour murs, plafonds et pièces de vie. Finitions haut de gamme par un artisan peintre avec 20 ans d\'expérience dans le Chablais.',
        'title' => 'Peinture intérieure',
        'subtitle' => 'Des murs et plafonds sublimes pour un intérieur qui vous ressemble.',
        'badge' => 'Intérieur',
        'tags' => ['Murs', 'Plafonds', 'Pièces de vie', 'Pièces d\'eau'],
        'color' => '#E8E0D4',
        'hero_image' => 'images/services/peinture-interieure-hero.webp',
        'card_image' => 'images/services/peinture-interieure-card.webp',
        'description' => [
            'La peinture intérieure est au cœur de mon expertise. Depuis plus de 20 ans, je transforme les espaces de vie de mes clients dans le Chablais en prenant soin de chaque détail, de la préparation des surfaces jusqu\'à la dernière couche de finition.',
            'Un résultat d\'exception ne s\'improvise pas. Il commence par un diagnostic précis de chaque surface : détection des fissures, traitement de l\'humidité, enduit de rebouchage et de lissage, ponçage soigné, application d\'une sous-couche adaptée. Ce travail invisible est la fondation d\'une peinture qui dure dans le temps et offre un rendu parfaitement uniforme.',
        ],
        'gallery' => [
            ['alt' => 'Chambre peinte en vert sauge', 'image' => 'images/services/peinture-interieure-gallery-1.webp'],
            ['alt' => 'Cuisine aux murs peints en blanc satin', 'image' => 'images/services/peinture-interieure-gallery-2.webp'],
            ['alt' => 'Salle de bains peinte en gris perle satin', 'image' => 'images/services/peinture-interieure-gallery-3.webp'],
            ['alt' => 'Détail d\'angle de mur peint avec précision', 'image' => 'images/services/peinture-interieure-gallery-4.webp'],
        ],
        'interventions' => [
            'Murs et plafonds de pièces de vie (salon, séjour, chambre)',
            'Pièces humides (salle de bains, cuisine) avec peintures spécifiques',
            'Cages d\'escalier et couloirs',
            'Plafonds hauts et surfaces difficiles d\'accès',
            'Préparation complète des supports (enduit, ponçage, sous-couche)',
            'Conseil en choix de teintes et finitions (mat, satin, brillant)',
        ],
        'cta_button' => 'Demander un devis pour votre intérieur',
        'related' => ['peinture-exterieure', 'peinture-decorative'],
    ],

    'peinture-exterieure' => [
        'meta_title' => 'Peinture extérieure à Évian et Thonon — Devigny Peinture, Haute-Savoie',
        'meta_description' => 'Peinture extérieure professionnelle : façades, volets, portails et clôtures. Protection et embellissement durables par un artisan peintre expérimenté dans le Chablais.',
        'title' => 'Peinture extérieure',
        'subtitle' => 'Protégez et embellissez votre habitat face aux éléments.',
        'badge' => 'Extérieur',
        'tags' => ['Façades', 'Volets', 'Portails', 'Clôtures'],
        'color' => '#C8D0C4',
        'hero_image' => 'images/services/peinture-exterieure-hero.webp',
        'card_image' => 'images/services/peinture-exterieure-card.webp',
        'description' => [
            'L\'extérieur de votre maison est sa première impression. Dans le Chablais, où les conditions climatiques — pluie, neige, variations de température — mettent les façades à rude épreuve, une peinture extérieure de qualité n\'est pas un luxe, c\'est une nécessité.',
            'Mon approche commence toujours par un diagnostic approfondi de l\'état des surfaces extérieures. J\'identifie les problèmes d\'adhérence, de décollement, de moisissure ou de fissuration avant de déterminer le traitement adapté. Cette étape cruciale garantit que la peinture appliquée tiendra dans la durée.',
        ],
        'gallery' => [
            ['alt' => 'Volets en bois peints en gris anthracite', 'image' => 'images/services/peinture-exterieure-gallery-1.webp'],
            ['alt' => 'Portail en fer peint par un professionnel', 'image' => 'images/services/peinture-exterieure-gallery-2.webp'],
            ['alt' => 'Bardage bois peint sur maison alpine', 'image' => 'images/services/peinture-exterieure-gallery-3.webp'],
            ['alt' => 'Clôture en bois peinte en blanc', 'image' => 'images/services/peinture-exterieure-gallery-4.webp'],
        ],
        'interventions' => [
            'Façades (enduit, crépi, peinture de finition)',
            'Volets et persiennes en bois ou métal',
            'Portails, clôtures et garde-corps',
            'Bardages bois et revêtements extérieurs',
            'Dessous de toits, bandeaux et gouttières',
            'Traitement et protection anti-humidité, anti-mousse',
        ],
        'cta_button' => 'Demander un devis pour vos extérieurs',
        'related' => ['ravalement-facade', 'boiseries-laquage'],
    ],

    'ravalement-facade' => [
        'meta_title' => 'Ravalement de façade à Évian et Thonon — Devigny Peinture, Haute-Savoie (74)',
        'meta_description' => 'Ravalement de façade professionnel dans le Chablais. Nettoyage, réparation, traitement et peinture de façade par un artisan peintre avec 20 ans d\'expérience.',
        'title' => 'Ravalement de façade',
        'subtitle' => 'Redonnez à votre façade son éclat d\'origine et protégez-la durablement.',
        'badge' => 'Façade',
        'tags' => ['Diagnostic', 'Nettoyage', 'Réparation', 'Peinture'],
        'color' => '#D0CCC4',
        'hero_image' => 'images/services/ravalement-facade-hero.webp',
        'card_image' => 'images/services/ravalement-facade-card.webp',
        'description' => [
            'Le ravalement de façade est une intervention complète qui va bien au-delà d\'un simple coup de peinture. C\'est une rénovation en profondeur de l\'enveloppe de votre maison, essentielle pour la protéger des intempéries et lui redonner toute sa beauté.',
            'Dans le Chablais, les façades subissent des conditions climatiques exigeantes : humidité du lac, gel hivernal, fortes pluies. Ces agressions fragilisent les enduits et favorisent l\'apparition de fissures, de mousses et de décollements. Un ravalement réalisé dans les règles de l\'art assure la pérennité de votre habitat.',
            'Mon processus est méthodique : nettoyage haute pression, traitement fongicide, réparation des fissures et éclats, application d\'un enduit de rénovation si nécessaire, puis peinture de finition en deux couches minimum avec des produits spécifiquement formulés pour les façades en zone alpine.',
        ],
        'gallery' => [
            ['alt' => 'Façade fraîchement ravalée en enduit blanc', 'image' => 'images/services/ravalement-facade-gallery-1.webp'],
            ['alt' => 'Détail de réparation de fissure sur façade', 'image' => 'images/services/ravalement-facade-gallery-2.webp'],
            ['alt' => 'Soubassement en pierre nettoyé et protégé', 'image' => 'images/services/ravalement-facade-gallery-3.webp'],
            ['alt' => 'Corniche et bandeau repeints sur façade', 'image' => 'images/services/ravalement-facade-gallery-4.webp'],
        ],
        'interventions' => [
            'Diagnostic complet de l\'état de la façade',
            'Nettoyage haute pression et traitement anti-mousse',
            'Réparation des fissures, éclats et décollements',
            'Application d\'enduit de rénovation et d\'imperméabilisation',
            'Peinture de façade en 2 couches minimum',
            'Peinture des éléments annexes (bandeaux, corniches, appuis de fenêtre)',
        ],
        'cta_button' => 'Demander un devis pour votre façade',
        'related' => ['peinture-exterieure', 'peinture-interieure'],
    ],

    'peinture-decorative' => [
        'meta_title' => 'Peinture décorative et enduits — Devigny Peinture, Évian & Thonon, Chablais',
        'meta_description' => 'Peinture décorative, enduits à la chaux, stuc, patines et effets spéciaux. Donnez du caractère à vos murs avec un artisan peintre spécialisé dans le Chablais.',
        'title' => 'Peinture décorative',
        'subtitle' => 'Des finitions d\'exception pour des intérieurs uniques.',
        'badge' => 'Décoratif',
        'tags' => ['Enduits', 'Patines', 'Effets', 'Stuc'],
        'color' => '#C8C0B8',
        'hero_image' => 'images/services/peinture-decorative-hero.webp',
        'card_image' => 'images/services/peinture-decorative-card.webp',
        'description' => [
            'La peinture décorative est l\'art de transformer un simple mur en une surface qui raconte une histoire. C\'est ici que mon expérience de plus de 20 ans prend tout son sens : chaque technique décorative demande un geste sûr, un œil exercé et une connaissance approfondie des matériaux.',
            'Que vous recherchiez la noblesse d\'un enduit à la chaux, la modernité d\'un effet béton ciré, la chaleur d\'une patine ou l\'élégance d\'un stuc vénitien, je maîtrise ces techniques artisanales pour créer des ambiances sur mesure qui reflètent votre personnalité.',
        ],
        'gallery' => [
            ['alt' => 'Mur en enduit béton ciré gris aux reflets soyeux', 'image' => 'images/services/peinture-decorative-gallery-1.webp'],
            ['alt' => 'Enduit à la chaux ton terre cuite dans un salon', 'image' => 'images/services/peinture-decorative-gallery-2.webp'],
            ['alt' => 'Stuc vénitien aux reflets nacrés dans une entrée', 'image' => 'images/services/peinture-decorative-gallery-3.webp'],
            ['alt' => 'Patine décorative effet vieilli sur un mur d\'accent', 'image' => 'images/services/peinture-decorative-gallery-4.webp'],
        ],
        'interventions' => [
            'Enduits décoratifs (chaux, tadelakt, stuc vénitien)',
            'Effet béton ciré et béton minéral',
            'Patines et glacis pour un effet vieilli ou antique',
            'Peinture à effets (métallisé, nacré, sablé)',
            'Fresques et murs d\'accent',
            'Conseil en décoration et association de textures',
        ],
        'cta_button' => 'Demander un devis décoratif',
        'related' => ['peinture-interieure', 'revetements-muraux'],
    ],

    'revetements-muraux' => [
        'meta_title' => 'Pose de papier peint et revêtements muraux — Devigny Peinture, Chablais (74)',
        'meta_description' => 'Pose professionnelle de papier peint, toile de verre et revêtements muraux décoratifs. Finitions soignées par un artisan qualifié à Évian, Thonon et dans le Chablais.',
        'title' => 'Revêtements muraux',
        'subtitle' => 'Papier peint, toile de verre et revêtements décoratifs posés avec maîtrise.',
        'badge' => 'Mural',
        'tags' => ['Papier peint', 'Toile de verre', 'Intissé', 'Panoramique'],
        'color' => '#DCD4C8',
        'hero_image' => 'images/services/revetements-muraux-hero.webp',
        'card_image' => 'images/services/revetements-muraux-card.webp',
        'description' => [
            'La pose de revêtements muraux est un art qui ne souffre aucune approximation. Un raccord mal aligné, une bulle d\'air, un décalage de motif : chaque imperfection se voit immédiatement. C\'est pourquoi ce travail exige un professionnel expérimenté.',
            'Je maîtrise la pose de tous types de revêtements : papier peint classique ou contemporain, papier peint panoramique grand format, toile de verre, intissé décoratif. La préparation du mur est là aussi déterminante : un support parfaitement lisse et enduit garantit une pose impeccable et un rendu final sans défaut.',
        ],
        'gallery' => [
            ['alt' => 'Papier peint panoramique forêt dans une chambre', 'image' => 'images/services/revetements-muraux-gallery-1.webp'],
            ['alt' => 'Papier peint motifs botaniques dorés dans un salon', 'image' => 'images/services/revetements-muraux-gallery-2.webp'],
            ['alt' => 'Toile de verre peinte en blanc dans un couloir', 'image' => 'images/services/revetements-muraux-gallery-3.webp'],
            ['alt' => 'Papier peint géométrique ton sur ton dans un bureau', 'image' => 'images/services/revetements-muraux-gallery-4.webp'],
        ],
        'interventions' => [
            'Pose de papier peint classique, intissé et vinyle',
            'Papier peint panoramique et sur mesure',
            'Toile de verre et fibre de verre à peindre',
            'Préparation des supports (décollement ancien papier, enduit, lissage)',
            'Revêtements muraux décoratifs et texturés',
            'Conseil dans le choix des motifs et références adaptées à chaque pièce',
        ],
        'cta_button' => 'Demander un devis revêtement mural',
        'related' => ['peinture-decorative', 'peinture-interieure'],
    ],

    'boiseries-laquage' => [
        'meta_title' => 'Laquage boiseries, portes et fenêtres — Devigny Peinture, Évian & Thonon',
        'meta_description' => 'Peinture et laquage professionnel de boiseries : portes, fenêtres, plinthes, escaliers. Finitions brillantes ou satinées impeccables par un artisan du Chablais.',
        'title' => 'Boiseries et laquage',
        'subtitle' => 'Des finitions irréprochables pour sublimer chaque élément bois de votre intérieur.',
        'badge' => 'Boiseries',
        'tags' => ['Portes', 'Fenêtres', 'Plinthes', 'Escaliers'],
        'color' => '#E0D8D0',
        'hero_image' => 'images/services/boiseries-laquage-hero.webp',
        'card_image' => 'images/services/boiseries-laquage-card.webp',
        'description' => [
            'Le laquage de boiseries est l\'une des prestations les plus exigeantes de mon métier. Obtenir une surface parfaitement lisse, sans coulure, sans trace de pinceau, avec un brillant uniforme, demande un savoir-faire que seule l\'expérience permet d\'acquérir.',
            'Chaque boiserie — porte, fenêtre, plinthe, escalier, placard — suit un protocole rigoureux : ponçage fin, dégraissage, application d\'un primaire d\'accrochage, puis deux à trois couches de laque avec un égrennage intermédiaire. Ce processus méticuleux est la garantie d\'un résultat qui durera des années.',
        ],
        'gallery' => [
            ['alt' => 'Porte à panneaux moulurés laquée blanc brillant', 'image' => 'images/services/boiseries-laquage-gallery-1.webp'],
            ['alt' => 'Plinthes et moulures laquées dans un salon', 'image' => 'images/services/boiseries-laquage-gallery-2.webp'],
            ['alt' => 'Escalier en bois repeint en blanc satin', 'image' => 'images/services/boiseries-laquage-gallery-3.webp'],
            ['alt' => 'Fenêtre intérieure et chambranle laqués', 'image' => 'images/services/boiseries-laquage-gallery-4.webp'],
        ],
        'interventions' => [
            'Laquage de portes et huisseries (brillant, satin, mat)',
            'Peinture de fenêtres et volets intérieurs',
            'Plinthes, moulures et corniches',
            'Escaliers et garde-corps',
            'Placards et dressings intégrés',
            'Remise en état de boiseries anciennes (décapage, traitement, finition)',
        ],
        'cta_button' => 'Demander un devis boiseries',
        'related' => ['peinture-interieure', 'peinture-exterieure'],
    ],

];
